"""Initial baseline migration

Revision ID: a675c9c6611e
Revises: f6cbae421c43
Create Date: 2025-10-31 15:32:42.999946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a675c9c6611e'
down_revision: Union[str, Sequence[str], None] = 'f6cbae421c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_findings_session'), table_name='audit_findings')
    op.drop_index(op.f('idx_audit_findings_severity'), table_name='audit_findings')
    op.drop_index(op.f('idx_audit_sessions_created'), table_name='audit_sessions')
    op.drop_index(op.f('idx_audit_sessions_status'), table_name='audit_sessions')
    op.drop_index(op.f('idx_audit_sessions_type'), table_name='audit_sessions')
    op.alter_column('babel_analysis_log', 'query_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original user query text',
               existing_nullable=False)
    op.alter_column('babel_analysis_log', 'language_detected',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ISO 639-1 language code (en, de, it, ja, etc.)',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'language_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence score for language detection (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fused sentiment score from FinBERT + Babel embeddings',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'fusion_boost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence boost from embedding fusion',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'embedding_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether Babel embeddings were used in analysis',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('babel_analysis_log', 'babel_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Status: success, degraded, failed, idle',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'processing_time_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total Babel node processing time',
               existing_nullable=True)
    op.drop_index(op.f('idx_babel_log_correlation_id'), table_name='babel_analysis_log')
    op.drop_index(op.f('idx_babel_log_created_at'), table_name='babel_analysis_log')
    op.drop_index(op.f('idx_babel_log_language'), table_name='babel_analysis_log')
    op.drop_index(op.f('idx_babel_log_user_id'), table_name='babel_analysis_log')
    op.drop_table_comment(
        'babel_analysis_log',
        existing_comment='Logs all Babel Gardens linguistic analysis for monitoring and analytics',
        schema=None
    )
    op.drop_index(op.f('idx_block_ticker_timestamp'), table_name='block_trades')
    op.drop_table_comment(
        'block_trades',
        existing_comment='Function P: Large block trades (>10k shares) indicating institutional activity',
        schema=None
    )
    op.drop_index(op.f('idx_coherence_timestamp'), table_name='coherence_logs')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_constraint(op.f('dark_pool_unique'), 'dark_pool_volume', type_='unique')
    op.drop_index(op.f('idx_dark_pool_ticker_date'), table_name='dark_pool_volume')
    op.drop_table_comment(
        'dark_pool_volume',
        existing_comment='Function P: Dark pool (off-exchange) volume tracking for institutional accumulation detection',
        schema=None
    )
    op.drop_index(op.f('idx_dependency_scans_session'), table_name='dependency_scans')
    op.drop_index(op.f('idx_docs_archive_doc_title'), table_name='docs_archive')
    op.drop_constraint(op.f('earnings_unique'), 'earnings_calendar', type_='unique')
    op.drop_index(op.f('idx_earnings_ticker_date'), table_name='earnings_calendar')
    op.drop_table_comment(
        'earnings_calendar',
        existing_comment='Function O: Earnings calendar for safety filtering (avoid holding during earnings)',
        schema=None
    )
    op.drop_index(op.f('idx_explanations_created_at'), table_name='explanations')
    op.drop_index(op.f('idx_explanations_ticker'), table_name='explanations')
    op.drop_index(op.f('idx_explanations_ticker_lang'), table_name='explanations')
    op.drop_index(op.f('idx_explanations_ticker_time'), table_name='explanations')
    op.drop_constraint(op.f('factor_scores_unique'), 'factor_scores', type_='unique')
    op.drop_index(op.f('idx_log_agent_agent_time'), table_name='log_agent')
    op.drop_index(op.f('idx_log_agent_payload_gin'), table_name='log_agent', postgresql_using='gin')
    op.drop_index(op.f('idx_log_agent_ticker_time'), table_name='log_agent')
    op.drop_constraint(op.f('macro_outlook_unique'), 'macro_outlook', type_='unique')
    op.drop_index(op.f('idx_memory_sync_timestamp'), table_name='memory_sync_logs')
    op.drop_index(op.f('idx_momentum_ticker_time'), table_name='momentum_logs')
    op.drop_index(op.f('momentum_logs_ticker_idx'), table_name='momentum_logs')
    op.drop_index(op.f('momentum_logs_ticker_timestamp_idx'), table_name='momentum_logs')
    op.drop_index(op.f('momentum_logs_timestamp_idx'), table_name='momentum_logs')
    op.drop_index(op.f('idx_ohlcv_ticker_dt'), table_name='ohlcv_daily')
    op.drop_index(op.f('idx_options_ticker_date'), table_name='options_flow')
    op.drop_constraint(op.f('options_flow_unique'), 'options_flow', type_='unique')
    op.drop_table_comment(
        'options_flow',
        existing_comment='Function P: Options volume and open interest for smart money sentiment',
        schema=None
    )
    op.drop_index(op.f('idx_sf_composite_desc'), table_name='screener_features')
    op.drop_index(op.f('idx_sf_sent_at'), table_name='screener_features')
    op.drop_index(op.f('idx_semantic_clusters_collection'), table_name='semantic_clusters')
    op.drop_index(op.f('idx_sent_ticker_time'), table_name='sentiment_scores')
    op.drop_index(op.f('idx_tickers_active_type'), table_name='tickers')
    op.drop_index(op.f('idx_tickers_fund_category'), table_name='tickers')
    op.drop_index(op.f('idx_tickers_isin'), table_name='tickers')
    op.drop_index(op.f('idx_tickers_provider'), table_name='tickers')
    op.drop_index(op.f('idx_tickers_sector'), table_name='tickers')
    op.drop_index(op.f('idx_tickers_type_active'), table_name='tickers')
    op.drop_index(op.f('idx_trend_ticker_time'), table_name='trend_logs')
    op.drop_constraint(op.f('unique_user_ticker'), 'user_holdings', type_='unique')
    op.drop_index(op.f('idx_vare_adaptations_param'), table_name='vare_adaptations')
    op.drop_index(op.f('idx_vare_adaptations_time'), table_name='vare_adaptations')
    op.drop_index(op.f('vault_delivery_jobs_created_at_idx'), table_name='vault_delivery_jobs')
    op.drop_index(op.f('vault_delivery_jobs_status_idx'), table_name='vault_delivery_jobs')
    op.drop_column('vault_delivery_jobs', 'destination_channels')
    op.drop_index(op.f('vault_events_created_at_idx'), table_name='vault_events')
    op.drop_index(op.f('vault_events_keeper_idx'), table_name='vault_events')
    op.drop_index(op.f('vault_history_created_at_idx'), table_name='vault_history')
    op.drop_index(op.f('vault_keepers_backups_created_at_idx'), table_name='vault_keepers_backups')
    op.drop_index(op.f('vault_keepers_backups_type_idx'), table_name='vault_keepers_backups')
    op.drop_index(op.f('idx_vola_ticker_time'), table_name='volatility_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vola_ticker_time'), 'volatility_logs', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('vault_keepers_backups_type_idx'), 'vault_keepers_backups', ['backup_type'], unique=False)
    op.create_index(op.f('vault_keepers_backups_created_at_idx'), 'vault_keepers_backups', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('vault_history_created_at_idx'), 'vault_history', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('vault_events_keeper_idx'), 'vault_events', ['keeper', 'event_type'], unique=False)
    op.create_index(op.f('vault_events_created_at_idx'), 'vault_events', [sa.literal_column('timestamp DESC')], unique=False)
    op.add_column('vault_delivery_jobs', sa.Column('destination_channels', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.create_index(op.f('vault_delivery_jobs_status_idx'), 'vault_delivery_jobs', ['status'], unique=False)
    op.create_index(op.f('vault_delivery_jobs_created_at_idx'), 'vault_delivery_jobs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_vare_adaptations_time'), 'vare_adaptations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_vare_adaptations_param'), 'vare_adaptations', ['parameter', sa.literal_column('created_at DESC')], unique=False)
    op.create_unique_constraint(op.f('unique_user_ticker'), 'user_holdings', ['user_id', 'ticker'])
    op.create_index(op.f('idx_trend_ticker_time'), 'trend_logs', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_tickers_type_active'), 'tickers', ['type', 'active'], unique=False)
    op.create_index(op.f('idx_tickers_sector'), 'tickers', ['sector'], unique=False)
    op.create_index(op.f('idx_tickers_provider'), 'tickers', ['provider'], unique=False)
    op.create_index(op.f('idx_tickers_isin'), 'tickers', ['isin'], unique=False)
    op.create_index(op.f('idx_tickers_fund_category'), 'tickers', ['fund_category'], unique=False)
    op.create_index(op.f('idx_tickers_active_type'), 'tickers', ['active', 'type'], unique=False)
    op.create_index(op.f('idx_sent_ticker_time'), 'sentiment_scores', ['ticker', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_semantic_clusters_collection'), 'semantic_clusters', ['collection'], unique=False)
    op.create_index(op.f('idx_sf_sent_at'), 'screener_features', [sa.literal_column('sentiment_at DESC')], unique=False)
    op.create_index(op.f('idx_sf_composite_desc'), 'screener_features', [sa.literal_column('composite_score DESC')], unique=False)
    op.create_table_comment(
        'options_flow',
        'Function P: Options volume and open interest for smart money sentiment',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('options_flow_unique'), 'options_flow', ['ticker', 'date', 'source'])
    op.create_index(op.f('idx_options_ticker_date'), 'options_flow', ['ticker', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_ohlcv_ticker_dt'), 'ohlcv_daily', ['ticker', sa.literal_column('dt DESC')], unique=False)
    op.create_index(op.f('momentum_logs_timestamp_idx'), 'momentum_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('momentum_logs_ticker_timestamp_idx'), 'momentum_logs', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('momentum_logs_ticker_idx'), 'momentum_logs', ['ticker'], unique=False)
    op.create_index(op.f('idx_momentum_ticker_time'), 'momentum_logs', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_memory_sync_timestamp'), 'memory_sync_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_unique_constraint(op.f('macro_outlook_unique'), 'macro_outlook', ['date', 'source'])
    op.create_index(op.f('idx_log_agent_ticker_time'), 'log_agent', ['ticker', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_log_agent_payload_gin'), 'log_agent', ['payload_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_log_agent_agent_time'), 'log_agent', ['agent', sa.literal_column('created_at DESC')], unique=False)
    op.create_unique_constraint(op.f('factor_scores_unique'), 'factor_scores', ['ticker', 'date'])
    op.create_index(op.f('idx_explanations_ticker_time'), 'explanations', ['ticker', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_explanations_ticker_lang'), 'explanations', ['ticker', 'language'], unique=False)
    op.create_index(op.f('idx_explanations_ticker'), 'explanations', ['ticker'], unique=False)
    op.create_index(op.f('idx_explanations_created_at'), 'explanations', ['created_at'], unique=False)
    op.create_table_comment(
        'earnings_calendar',
        'Function O: Earnings calendar for safety filtering (avoid holding during earnings)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_earnings_ticker_date'), 'earnings_calendar', ['ticker', sa.literal_column('earnings_date DESC')], unique=False)
    op.create_unique_constraint(op.f('earnings_unique'), 'earnings_calendar', ['ticker', 'earnings_date', 'fiscal_quarter'])
    op.create_index(op.f('idx_docs_archive_doc_title'), 'docs_archive', ['doc_title'], unique=False)
    op.create_index(op.f('idx_dependency_scans_session'), 'dependency_scans', ['audit_session_id'], unique=False)
    op.create_table_comment(
        'dark_pool_volume',
        'Function P: Dark pool (off-exchange) volume tracking for institutional accumulation detection',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_dark_pool_ticker_date'), 'dark_pool_volume', ['ticker', sa.literal_column('date DESC')], unique=False)
    op.create_unique_constraint(op.f('dark_pool_unique'), 'dark_pool_volume', ['ticker', 'date', 'source'])
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_coherence_timestamp'), 'coherence_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_table_comment(
        'block_trades',
        'Function P: Large block trades (>10k shares) indicating institutional activity',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_block_ticker_timestamp'), 'block_trades', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_table_comment(
        'babel_analysis_log',
        'Logs all Babel Gardens linguistic analysis for monitoring and analytics',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_babel_log_user_id'), 'babel_analysis_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_babel_log_language'), 'babel_analysis_log', ['language_detected'], unique=False)
    op.create_index(op.f('idx_babel_log_created_at'), 'babel_analysis_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_babel_log_correlation_id'), 'babel_analysis_log', ['correlation_id'], unique=False)
    op.alter_column('babel_analysis_log', 'processing_time_ms',
               existing_type=sa.INTEGER(),
               comment='Total Babel node processing time',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'babel_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: success, degraded, failed, idle',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'embedding_used',
               existing_type=sa.BOOLEAN(),
               comment='Whether Babel embeddings were used in analysis',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('babel_analysis_log', 'fusion_boost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence boost from embedding fusion',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fused sentiment score from FinBERT + Babel embeddings',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'language_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score for language detection (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'language_detected',
               existing_type=sa.VARCHAR(length=10),
               comment='ISO 639-1 language code (en, de, it, ja, etc.)',
               existing_nullable=True)
    op.alter_column('babel_analysis_log', 'query_text',
               existing_type=sa.TEXT(),
               comment='Original user query text',
               existing_nullable=False)
    op.create_index(op.f('idx_audit_sessions_type'), 'audit_sessions', ['audit_type'], unique=False)
    op.create_index(op.f('idx_audit_sessions_status'), 'audit_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_audit_sessions_created'), 'audit_sessions', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_findings_severity'), 'audit_findings', ['severity'], unique=False)
    op.create_index(op.f('idx_audit_findings_session'), 'audit_findings', ['audit_session_id'], unique=False)
    # ### end Alembic commands ###
