"""
E2E Test: Qdrant Vector Operations
====================================
Verifies upsert, search, and delete operations on Qdrant using
real embeddings generated by the Embedding API.

Requires: Qdrant (localhost:9333), Embedding API (localhost:9010).
"""
import uuid

import httpx
import pytest

pytestmark = [pytest.mark.e2e]

E2E_COLLECTION = "e2e_test_vectors"


@pytest.fixture(scope="module")
def qdrant_collection(qdrant_http):
    """Create a test collection and clean up after."""
    # Create collection with 768 dimensions (nomic-embed-text-v1.5)
    r = httpx.put(
        f"{qdrant_http}/collections/{E2E_COLLECTION}",
        json={
            "vectors": {"size": 768, "distance": "Cosine"},
        },
        timeout=10.0,
    )
    assert r.status_code in (200, 409), f"Failed to create collection: {r.text}"

    yield E2E_COLLECTION

    # Cleanup
    httpx.delete(f"{qdrant_http}/collections/{E2E_COLLECTION}", timeout=10.0)


def _get_embedding(embedding_api: str, text: str) -> list:
    """Get embedding vector from the Embedding API."""
    r = httpx.post(
        f"{embedding_api}/v1/embeddings/create",
        json={"text": text, "source": "e2e_test"},
        timeout=15.0,
    )
    assert r.status_code == 200, f"Embedding API error: {r.text[:200]}"
    data = r.json()
    assert data.get("success"), f"Embedding not successful: {data}"
    return data["embedding"]


class TestCollectionManagement:
    """Collection CRUD operations."""

    def test_create_collection(self, qdrant_http):
        """Create a temporary collection."""
        name = f"e2e_temp_{uuid.uuid4().hex[:8]}"
        r = httpx.put(
            f"{qdrant_http}/collections/{name}",
            json={"vectors": {"size": 768, "distance": "Cosine"}},
            timeout=10.0,
        )
        assert r.status_code == 200
        assert r.json().get("result") is True

        # Verify it exists
        r2 = httpx.get(f"{qdrant_http}/collections/{name}", timeout=5.0)
        assert r2.status_code == 200

        # Cleanup
        httpx.delete(f"{qdrant_http}/collections/{name}", timeout=5.0)

    def test_list_collections(self, qdrant_http):
        """Collections listing must work."""
        r = httpx.get(f"{qdrant_http}/collections", timeout=5.0)
        assert r.status_code == 200
        data = r.json()
        assert "result" in data
        assert "collections" in data["result"]

    @pytest.mark.parametrize("collection", [
        "entity_embeddings",
        "phrases_embeddings",
        "semantic_states",
        "conversations_embeddings",
        "weave_embeddings",
    ])
    def test_contract_collections_exist(self, qdrant_http, collection):
        """All RAG contract collections (CORE + ORDER) must exist."""
        r = httpx.get(f"{qdrant_http}/collections/{collection}", timeout=5.0)
        assert r.status_code == 200, f"Collection {collection} missing from Qdrant"


class TestEmbeddingGeneration:
    """Embedding API must produce valid vectors."""

    def test_single_embedding(self, embedding_api):
        """Generate a single embedding and validate dimensions."""
        vec = _get_embedding(embedding_api, "test di embedding vettoriale")
        assert isinstance(vec, list)
        assert len(vec) == 768
        assert all(isinstance(v, float) for v in vec)

    def test_embedding_deterministic(self, embedding_api):
        """Same text must produce identical embeddings."""
        text = "deterministic embedding test"
        vec1 = _get_embedding(embedding_api, text)
        vec2 = _get_embedding(embedding_api, text)
        assert vec1 == vec2

    def test_different_texts_different_vectors(self, embedding_api):
        """Different texts must produce different embeddings."""
        vec1 = _get_embedding(embedding_api, "il sole splende forte")
        vec2 = _get_embedding(embedding_api, "la pioggia cade lenta")
        assert vec1 != vec2

    def test_batch_embeddings(self, embedding_api):
        """Batch embedding endpoint must work."""
        r = httpx.post(
            f"{embedding_api}/v1/embeddings/batch",
            json={"texts": ["testo uno", "testo due", "testo tre"], "source": "e2e"},
            timeout=15.0,
        )
        assert r.status_code == 200
        data = r.json()
        assert data.get("success")
        embeddings = data.get("embeddings", [])
        assert len(embeddings) == 3
        assert all(len(e) == 768 for e in embeddings)


class TestUpsertAndSearch:
    """Upsert vectors and search for similarity."""

    def test_upsert_single_point(self, qdrant_http, embedding_api, qdrant_collection):
        """Upsert a single vector point."""
        vec = _get_embedding(embedding_api, "intelligenza artificiale generativa")
        point_id = str(uuid.uuid4())

        r = httpx.put(
            f"{qdrant_http}/collections/{qdrant_collection}/points",
            json={
                "points": [{
                    "id": point_id,
                    "vector": vec,
                    "payload": {"text": "intelligenza artificiale generativa", "source": "e2e"},
                }]
            },
            timeout=10.0,
        )
        assert r.status_code == 200, f"Upsert failed: {r.text}"

    def test_upsert_multiple_points(self, qdrant_http, embedding_api, qdrant_collection):
        """Upsert 3 vectors with different content."""
        texts = [
            "machine learning supervisionato",
            "reti neurali profonde",
            "elaborazione del linguaggio naturale",
        ]
        points = []
        for text in texts:
            vec = _get_embedding(embedding_api, text)
            points.append({
                "id": str(uuid.uuid4()),
                "vector": vec,
                "payload": {"text": text, "source": "e2e"},
            })

        r = httpx.put(
            f"{qdrant_http}/collections/{qdrant_collection}/points",
            json={"points": points},
            timeout=15.0,
        )
        assert r.status_code == 200

    def test_search_returns_similar_vectors(self, qdrant_http, embedding_api, qdrant_collection):
        """Search must return relevant results ordered by similarity."""
        # First upsert some known content
        texts = [
            "analisi dei dati con python",
            "programmazione funzionale",
            "architettura dei microservizi",
        ]
        for text in texts:
            vec = _get_embedding(embedding_api, text)
            httpx.put(
                f"{qdrant_http}/collections/{qdrant_collection}/points",
                json={"points": [{"id": str(uuid.uuid4()), "vector": vec, "payload": {"text": text}}]},
                timeout=10.0,
            )

        # Wait for indexing
        import time
        time.sleep(1)

        # Search for something similar to "analisi dei dati"
        query_vec = _get_embedding(embedding_api, "analisi dei dati")
        r = httpx.post(
            f"{qdrant_http}/collections/{qdrant_collection}/points/search",
            json={"vector": query_vec, "top": 3, "with_payload": True},
            timeout=10.0,
        )
        assert r.status_code == 200
        results = r.json().get("result", [])
        assert len(results) > 0, "Search returned no results"

        # Results should be ordered by score (descending)
        scores = [r["score"] for r in results]
        assert scores == sorted(scores, reverse=True), "Results not ordered by score"

    def test_search_payload_returned(self, qdrant_http, embedding_api, qdrant_collection):
        """Search results must include payload when requested."""
        # Upsert with rich payload
        vec = _get_embedding(embedding_api, "test payload completo")
        point_id = str(uuid.uuid4())
        httpx.put(
            f"{qdrant_http}/collections/{qdrant_collection}/points",
            json={"points": [{
                "id": point_id,
                "vector": vec,
                "payload": {"text": "test payload completo", "source": "e2e", "category": "test"},
            }]},
            timeout=10.0,
        )

        import time
        time.sleep(1)

        # Search and verify payload
        r = httpx.post(
            f"{qdrant_http}/collections/{qdrant_collection}/points/search",
            json={"vector": vec, "top": 1, "with_payload": True},
            timeout=10.0,
        )
        assert r.status_code == 200
        results = r.json().get("result", [])
        assert len(results) >= 1
        # Top result should have our payload
        payload = results[0].get("payload", {})
        assert payload.get("source") == "e2e"


class TestPointCount:
    """Verify point counting works."""

    def test_collection_point_count(self, qdrant_http, qdrant_collection):
        """Point count must be retrievable."""
        r = httpx.get(
            f"{qdrant_http}/collections/{qdrant_collection}",
            timeout=5.0,
        )
        assert r.status_code == 200
        info = r.json().get("result", {})
        count = info.get("points_count", -1)
        assert isinstance(count, int)
        assert count >= 0


class TestDeleteOperations:
    """Verify point deletion works."""

    def test_delete_by_id(self, qdrant_http, embedding_api, qdrant_collection):
        """Delete a point by ID and verify it's gone."""
        # Upsert a point
        vec = _get_embedding(embedding_api, "punto da cancellare")
        point_id = str(uuid.uuid4())
        httpx.put(
            f"{qdrant_http}/collections/{qdrant_collection}/points",
            json={"points": [{"id": point_id, "vector": vec, "payload": {"text": "da cancellare"}}]},
            timeout=10.0,
        )

        import time
        time.sleep(1)

        # Get count before
        r = httpx.get(f"{qdrant_http}/collections/{qdrant_collection}", timeout=5.0)
        before = r.json()["result"]["points_count"]

        # Delete
        r = httpx.post(
            f"{qdrant_http}/collections/{qdrant_collection}/points/delete",
            json={"points": [point_id]},
            timeout=10.0,
        )
        assert r.status_code == 200

        time.sleep(1)

        # Count should decrease
        r = httpx.get(f"{qdrant_http}/collections/{qdrant_collection}", timeout=5.0)
        after = r.json()["result"]["points_count"]
        assert after < before, f"Point not deleted: before={before}, after={after}"
