"""
Portfolio Guardian Agent - Sacred Order #7 (Mercator)
Portfolio monitoring and proactive insights generation

🛡️ MISSION: Monitor shadow portfolios and generate actionable insights
🎯 CAPABILITIES:
  1. Risk alerts (concentration, volatility, drawdown)
  2. Opportunity detection (underweight sectors, momentum shifts)
  3. Rebalancing suggestions (drift from target allocation)
  4. Market regime changes (bull/bear transitions)
  5. Performance attribution (winners/losers analysis)

Architecture:
- Input: shadow_portfolio_snapshots (PostgreSQL)
- Analysis: VARE risk scores, Neural Engine updates, market data
- Output: guardian_insights (PostgreSQL) + Redis events
- Cadence: Hourly via cron job

Author: Vitruvyan AI Team
Created: January 12, 2026
"""

from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from enum import Enum
import logging
import json
import os
import numpy as np

from core.agents.postgres_agent import PostgresAgent
from core.agents.qdrant_agent import QdrantAgent

# VEE + ChatGPT conversational layer
try:
    from core.vpar.vee.vee_engine import VEEEngine
    VEE_AVAILABLE = True
except ImportError:
    VEE_AVAILABLE = False
    
try:
    import openai
    OPENAI_AVAILABLE = True
    openai.api_key = os.getenv("OPENAI_API_KEY")
except ImportError:
    OPENAI_AVAILABLE = False

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ========================= Enums & Data Classes =========================

class InsightType(Enum):
    """5 types of guardian insights"""
    RISK_ALERT = "risk_alert"                      # Type 1: Risk concentration/volatility
    OPPORTUNITY = "opportunity"                     # Type 2: Market opportunities
    REBALANCE = "rebalance"                        # Type 3: Portfolio drift
    REGIME_CHANGE = "regime_change"                # Type 4: Market regime shift
    PERFORMANCE_ATTRIBUTION = "performance_attribution"  # Type 5: Winners/losers


class InsightSeverity(Enum):
    """Insight urgency levels"""
    INFO = "info"           # Informational only
    WARNING = "warning"     # Attention recommended
    CRITICAL = "critical"   # Action required


class RiskCategory(Enum):
    """Risk categorization"""
    CONCENTRATION = "concentration"      # Single position too large
    VOLATILITY = "volatility"           # Portfolio too volatile
    DRAWDOWN = "drawdown"               # Significant losses
    CORRELATION = "correlation"         # Over-correlated positions
    LIQUIDITY = "liquidity"            # Low-volume holdings


@dataclass
class GuardianInsight:
    """Portfolio insight generated by Guardian"""
    insight_id: Optional[int] = None
    user_id: str = ""
    snapshot_id: int = 0
    insight_type: str = ""  # InsightType enum value
    severity: str = ""      # InsightSeverity enum value
    title: str = ""
    description: str = ""
    metrics: Dict[str, Any] = None
    recommendations: List[str] = None
    vee_explanations: Dict[str, str] = None  # NEW: VEE 3-level narratives
    conversational_summary: str = ""  # NEW: ChatGPT natural summary
    created_at: Optional[datetime] = None
    
    def __post_init__(self):
        if self.metrics is None:
            self.metrics = {}
        if self.recommendations is None:
            self.recommendations = []
        if self.vee_explanations is None:
            self.vee_explanations = {}


# ========================= Portfolio Guardian Agent =========================

class PortfolioGuardianAgent:
    """
    Portfolio Guardian Agent
    
    Monitors shadow portfolios and generates 5 types of insights:
    1. Risk alerts (concentration, volatility, drawdown)
    2. Opportunities (underweight sectors, momentum shifts)
    3. Rebalancing (drift from target allocation)
    4. Regime changes (market bull/bear transitions)
    5. Performance attribution (winners/losers)
    
    Usage:
        guardian = PortfolioGuardianAgent(postgres_agent=pg)
        insights = guardian.analyze_portfolio(user_id="beta_user_01")
    """
    
    def __init__(
        self,
        postgres_agent: PostgresAgent,
        qdrant_agent: Optional[QdrantAgent] = None,
        risk_thresholds: Optional[Dict[str, float]] = None,
        conversational_mode: bool = True  # NEW: Enable VEE + ChatGPT fallback
    ):
        """
        Initialize Portfolio Guardian
        
        Args:
            postgres_agent: PostgreSQL connection
            qdrant_agent: Qdrant vector DB (optional, for semantic insights)
            risk_thresholds: Custom risk thresholds (optional)
            conversational_mode: Enable VEE + ChatGPT for natural insights (default: True)
        """
        self.postgres = postgres_agent
        self.qdrant = qdrant_agent or QdrantAgent()
        self.conversational_mode = conversational_mode
        
        # Initialize VEE engine if available
        if conversational_mode and VEE_AVAILABLE:
            self.vee_engine = VEEEngine()  # VEEEngine has no __init__ params
            logger.info("✅ VEE Engine initialized for conversational insights")
        else:
            self.vee_engine = None
            if conversational_mode:
                logger.warning("⚠️ VEE Engine not available, will use ChatGPT fallback")
        
        # Default risk thresholds
        self.risk_thresholds = risk_thresholds or {
            "max_position_weight": 0.30,      # 30% max single position
            "concentration_risk": 0.40,        # 40% max single sector
            "max_volatility": 0.35,           # 35% annualized vol
            "max_drawdown": 0.15,             # 15% max drawdown
            "correlation_threshold": 0.80,     # 80% max correlation
            "rebalance_drift": 0.10           # 10% drift triggers rebalance
        }
        
        logger.info("🛡️ PortfolioGuardianAgent initialized (Sacred Order #7)")
        logger.info(f"   Conversational Mode: {conversational_mode}")
        logger.info(f"   VEE: {VEE_AVAILABLE}, OpenAI: {OPENAI_AVAILABLE}")
    
    def analyze_portfolio(
        self,
        user_id: str,
        snapshot_id: Optional[int] = None
    ) -> List[GuardianInsight]:
        """
        Analyze portfolio and generate insights
        
        Args:
            user_id: User identifier
            snapshot_id: Specific snapshot ID (None = latest)
        
        Returns:
            List of GuardianInsight objects
        """
        logger.info(f"🛡️ Guardian analysis started - User: {user_id}")
        
        # Get latest portfolio snapshot
        snapshot = self._get_portfolio_snapshot(user_id, snapshot_id)
        if not snapshot:
            logger.warning(f"⚠️ No portfolio found for user {user_id}")
            return []
        
        insights = []
        
        # Type 1: Risk Alerts
        risk_insights = self._analyze_risk_alerts(snapshot)
        insights.extend(risk_insights)
        
        # Type 2: Opportunities
        opportunity_insights = self._analyze_opportunities(snapshot)
        insights.extend(opportunity_insights)
        
        # Type 3: Rebalancing
        rebalance_insights = self._analyze_rebalancing(snapshot)
        insights.extend(rebalance_insights)
        
        # Type 4: Regime Changes
        regime_insights = self._analyze_regime_changes(snapshot)
        insights.extend(regime_insights)
        
        # Type 5: Performance Attribution
        perf_insights = self._analyze_performance(snapshot)
        insights.extend(perf_insights)
        
        # NEW: Enhance all insights with VEE + ChatGPT conversational narratives
        if self.conversational_mode:
            logger.info("🎨 Enhancing insights with VEE conversational narratives...")
            enhanced_insights = []
            for insight in insights:
                enhanced = self._enhance_with_vee_narratives(insight)
                enhanced_insights.append(enhanced)
            insights = enhanced_insights
        
        # Save insights to database
        for insight in insights:
            self._save_insight(insight)
        
        logger.info(f"✅ Guardian analysis complete - {len(insights)} insights generated")
        return insights
    
    def _get_portfolio_snapshot(
        self,
        user_id: str,
        snapshot_id: Optional[int] = None
    ) -> Optional[Dict[str, Any]]:
        """Retrieve portfolio snapshot from database"""
        with self.postgres.connection.cursor() as cur:
            if snapshot_id:
                cur.execute("""
                    SELECT * FROM shadow_portfolio_snapshots
                    WHERE snapshot_id = %s AND user_id = %s
                """, (snapshot_id, user_id))
            else:
                cur.execute("""
                    SELECT * FROM shadow_portfolio_snapshots
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                """, (user_id,))
            
            row = cur.fetchone()
            if not row:
                return None
            
            # Convert to dict
            columns = [desc[0] for desc in cur.description]
            return dict(zip(columns, row))
    
    # ========================= Type 1: Risk Alerts =========================
    
    def _analyze_risk_alerts(self, snapshot: Dict[str, Any]) -> List[GuardianInsight]:
        """Analyze concentration, volatility, and drawdown risks"""
        insights = []
        risk_metrics = snapshot.get("risk_metrics", {})
        holdings = snapshot.get("holdings", [])
        
        # Risk 1: Concentration Risk
        max_position = risk_metrics.get("max_position_weight", 0.0)
        if max_position > self.risk_thresholds["max_position_weight"]:
            # Find ticker with max weight
            max_ticker = max(holdings, key=lambda h: h.get("weight", 0.0))["ticker"] if holdings else "Unknown"
            current_pct = max_position * 100
            target_low = self.risk_thresholds["max_position_weight"] * 100 * 0.85  # Slightly below threshold
            target_high = self.risk_thresholds["max_position_weight"] * 100
            reduction_pct = current_pct - target_high
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.RISK_ALERT.value,
                severity=InsightSeverity.WARNING.value,
                title="High Position Concentration",
                description=f"Single position represents {max_position*100:.1f}% of portfolio (threshold: {self.risk_thresholds['max_position_weight']*100:.0f}%)",
                metrics={
                    "max_position_weight": max_position,
                    "threshold": self.risk_thresholds["max_position_weight"],
                    "risk_category": RiskCategory.CONCENTRATION.value,
                    "max_ticker": max_ticker
                },
                recommendations=[
                    f"Reduce {max_ticker} concentration to {target_low:.0f}-{target_high:.0f}% (currently {current_pct:.1f}%)",
                    f"Portfolio should maintain max {target_high:.0f}% per position for adequate diversification",
                    f"Risk reduction: -{reduction_pct:.1f}pp concentration exposure"
                ]
            ))
        
        # Risk 2: High Average Risk Score
        avg_risk = risk_metrics.get("average_risk_score", 0.5)
        if avg_risk > 0.70:
            num_high_risk = sum(1 for h in holdings if h.get("risk_score", 0.5) > 0.70)
            target_risk = 0.60  # Target average risk score
            risk_reduction_pct = ((avg_risk - target_risk) / avg_risk) * 100
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.RISK_ALERT.value,
                severity=InsightSeverity.WARNING.value,
                title="High Portfolio Risk Score",
                description=f"Average VARE risk score {avg_risk:.2f} indicates elevated volatility exposure",
                metrics={
                    "average_risk_score": avg_risk,
                    "num_high_risk_positions": num_high_risk,
                    "risk_category": RiskCategory.VOLATILITY.value,
                    "target_risk_score": target_risk
                },
                recommendations=[
                    f"Reduce portfolio average risk score to {target_risk:.2f} (currently {avg_risk:.2f})",
                    f"Increase allocation to defensive sectors by {risk_reduction_pct:.0f}pp (Utilities, Consumer Staples, Healthcare)",
                    f"{num_high_risk} high-risk positions detected - consider reducing total exposure to high-volatility tickers"
                ]
            ))
        
        # Risk 3: Low Diversification
        diversification = risk_metrics.get("diversification_score", 0.5)
        if diversification < 0.40:
            num_holdings = risk_metrics.get("num_holdings", 0)
            target_diversification = 0.65  # Target diversification score
            improvement_needed = ((target_diversification - diversification) / diversification) * 100
            recommended_holdings = max(8, num_holdings + 3)  # Suggest at least 8 positions
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.RISK_ALERT.value,
                severity=InsightSeverity.INFO.value,
                title="Low Portfolio Diversification",
                description=f"Diversification score {diversification:.2f} suggests concentrated holdings",
                metrics={
                    "diversification_score": diversification,
                    "num_holdings": num_holdings,
                    "risk_category": RiskCategory.CONCENTRATION.value,
                    "target_diversification": target_diversification,
                    "recommended_holdings": recommended_holdings
                },
                recommendations=[
                    f"Increase diversification score to {target_diversification:.2f} (currently {diversification:.2f}, +{improvement_needed:.0f}% improvement needed)",
                    f"Expand portfolio to {recommended_holdings} holdings (currently {num_holdings}) across underrepresented sectors",
                    f"Target allocation: max 15-20% per holding to achieve balanced diversification"
                ]
            ))
        
        return insights
    
    # ========================= Type 2: Opportunities =========================
    
    def _analyze_opportunities(self, snapshot: Dict[str, Any]) -> List[GuardianInsight]:
        """Detect market opportunities (underweight sectors, momentum shifts)"""
        insights = []
        sector_breakdown = snapshot.get("sector_breakdown", {})
        
        # Opportunity 1: Underweight Sectors
        # Compare current allocation vs market cap weights (simplified: assume equal optimal)
        optimal_weight = 1.0 / max(len(sector_breakdown), 1)
        underweight_sectors = []
        
        for sector, weight in sector_breakdown.items():
            if sector != "Unknown" and weight < optimal_weight * 0.50:  # <50% of optimal
                underweight_sectors.append((sector, weight, optimal_weight))
        
        if underweight_sectors:
            # Calculate target allocation increase
            top_underweight = underweight_sectors[0]
            sector_name = top_underweight[0]
            current_weight_pct = top_underweight[1] * 100
            target_weight_pct = optimal_weight * 100
            allocation_gap_pct = target_weight_pct - current_weight_pct
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.OPPORTUNITY.value,
                severity=InsightSeverity.INFO.value,
                title="Underweight Sector Opportunities",
                description=f"Portfolio underweight in {len(underweight_sectors)} sectors",
                metrics={
                    "underweight_sectors": [s[0] for s in underweight_sectors],
                    "current_weights": {s[0]: s[1] for s in underweight_sectors},
                    "optimal_weight": optimal_weight
                },
                recommendations=[
                    f"Increase {sector_name} allocation to {target_weight_pct:.0f}% (currently {current_weight_pct:.1f}%, gap: +{allocation_gap_pct:.1f}pp)",
                    f"Add {len(underweight_sectors)} sector{'s' if len(underweight_sectors) > 1 else ''} to achieve balanced diversification",
                    f"Diversification benefit: +{len(underweight_sectors) * 10:.0f}% risk reduction potential"
                ]
            ))
        
        # Opportunity 2: High Cash Balance
        cash_available = snapshot.get("cash_available", 0.0)
        total_value = snapshot.get("total_value", 1.0)
        cash_pct = cash_available / total_value if total_value > 0 else 0.0
        
        if cash_pct > 0.20:  # >20% cash
            target_cash_pct = 10.0  # Target 10% cash reserve
            deployable_pct = (cash_pct * 100) - target_cash_pct
            deployable_amount = cash_available * (deployable_pct / (cash_pct * 100))
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.OPPORTUNITY.value,
                severity=InsightSeverity.INFO.value,
                title="High Cash Balance",
                description=f"{cash_pct*100:.1f}% portfolio in cash - consider deployment",
                metrics={
                    "cash_percentage": cash_pct,
                    "cash_amount": cash_available,
                    "deployable_amount": deployable_amount,
                    "target_cash_percentage": target_cash_pct / 100
                },
                recommendations=[
                    f"Reduce cash allocation to {target_cash_pct:.0f}% (currently {cash_pct*100:.1f}%, deployable: ${deployable_amount:,.0f})",
                    f"Deploy {deployable_pct:.0f}pp excess cash across high-conviction positions (3-5 holdings)",
                    f"Target allocation: {deployable_pct/3:.0f}pp per new position for dollar-cost averaging"
                ]
            ))
        
        return insights
    
    # ========================= Type 3: Rebalancing =========================
    
    def _analyze_rebalancing(self, snapshot: Dict[str, Any]) -> List[GuardianInsight]:
        """Detect portfolio drift requiring rebalancing"""
        insights = []
        holdings = snapshot.get("holdings", [])
        risk_metrics = snapshot.get("risk_metrics", {})
        
        # Rebalance 1: Weight Drift Detection
        # Compare current weights vs initial target (assumed equal-weight)
        num_holdings = len(holdings)
        if num_holdings == 0:
            return insights
        
        target_weight = 1.0 / num_holdings
        drift_detected = False
        drifted_positions = []
        
        for holding in holdings:
            current_weight = holding.get("weight", 0.0)
            drift = abs(current_weight - target_weight)
            
            if drift > self.risk_thresholds["rebalance_drift"]:
                drift_detected = True
                drifted_positions.append({
                    "ticker": holding.get("ticker"),
                    "current_weight": current_weight,
                    "target_weight": target_weight,
                    "drift": drift
                })
        
        if drift_detected:
            # Find most drifted positions
            overweight = [p for p in drifted_positions if p["current_weight"] > p["target_weight"]]
            underweight = [p for p in drifted_positions if p["current_weight"] < p["target_weight"]]
            
            # Calculate total rebalancing magnitude
            total_drift_pct = sum(p["drift"] for p in drifted_positions) * 100
            
            recommendations = []
            if overweight:
                top_overweight = max(overweight, key=lambda p: p["drift"])
                recommendations.append(
                    f"Reduce {top_overweight['ticker']} to {top_overweight['target_weight']*100:.0f}% "
                    f"(currently {top_overweight['current_weight']*100:.1f}%, "
                    f"drift: +{top_overweight['drift']*100:.1f}pp)"
                )
            
            if underweight:
                top_underweight = max(underweight, key=lambda p: p["drift"])
                recommendations.append(
                    f"Increase {top_underweight['ticker']} to {top_underweight['target_weight']*100:.0f}% "
                    f"(currently {top_underweight['current_weight']*100:.1f}%, "
                    f"drift: -{top_underweight['drift']*100:.1f}pp)"
                )
            
            recommendations.append(
                f"Total portfolio drift: {total_drift_pct:.1f}pp across {len(drifted_positions)} positions - "
                f"rebalance to restore {target_weight*100:.0f}% equal-weight allocation"
            )
            
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.REBALANCE.value,
                severity=InsightSeverity.WARNING.value,
                title="Portfolio Rebalancing Recommended",
                description=f"{len(drifted_positions)} positions drifted beyond {self.risk_thresholds['rebalance_drift']*100:.0f}% threshold",
                metrics={
                    "drifted_positions": drifted_positions,
                    "threshold": self.risk_thresholds["rebalance_drift"],
                    "total_drift": total_drift_pct / 100
                },
                recommendations=recommendations
            ))
        
        return insights
    
    # ========================= Type 4: Regime Changes =========================
    
    def _analyze_regime_changes(self, snapshot: Dict[str, Any]) -> List[GuardianInsight]:
        """Detect market regime changes (bull/bear transitions)"""
        insights = []
        
        # TODO: Implement real regime detection using:
        # - SPY moving averages (50-day, 200-day crossover)
        # - VIX levels (fear index)
        # - Market breadth indicators
        # - Economic indicators
        
        # For MVP: Placeholder logic
        # Check average risk score as proxy for market stress
        risk_metrics = snapshot.get("risk_metrics", {})
        avg_risk = risk_metrics.get("average_risk_score", 0.5)
        
        if avg_risk > 0.75:
            insights.append(GuardianInsight(
                user_id=snapshot["user_id"],
                snapshot_id=snapshot["snapshot_id"],
                insight_type=InsightType.REGIME_CHANGE.value,
                severity=InsightSeverity.WARNING.value,
                title="Elevated Market Risk Detected",
                description="Portfolio risk metrics suggest heightened market volatility",
                metrics={
                    "average_risk_score": avg_risk,
                    "regime_proxy": "high_volatility"
                },
                recommendations=[
                    "Consider defensive positioning",
                    "Review stop-loss levels",
                    "Reduce leverage if applicable"
                ]
            ))
        
        return insights
    
    # ========================= Type 5: Performance Attribution =========================
    
    def _analyze_performance(self, snapshot: Dict[str, Any]) -> List[GuardianInsight]:
        """Analyze winners/losers in portfolio"""
        insights = []
        holdings = snapshot.get("holdings", [])
        
        if not holdings:
            return insights
        
        # Sort holdings by composite_z (proxy for performance)
        sorted_holdings = sorted(
            holdings,
            key=lambda h: h.get("composite_z", 0.0),
            reverse=True
        )
        
        # Top performers
        top_3 = sorted_holdings[:3]
        bottom_3 = sorted_holdings[-3:] if len(sorted_holdings) >= 3 else []
        
        insights.append(GuardianInsight(
            user_id=snapshot["user_id"],
            snapshot_id=snapshot["snapshot_id"],
            insight_type=InsightType.PERFORMANCE_ATTRIBUTION.value,
            severity=InsightSeverity.INFO.value,
            title="Portfolio Performance Attribution",
            description=f"Top performers: {', '.join([h.get('ticker') for h in top_3])}",
            metrics={
                "top_performers": [
                    {
                        "ticker": h.get("ticker"),
                        "weight": h.get("weight"),
                        "composite_z": h.get("composite_z"),
                        "risk_score": h.get("risk_score")
                    }
                    for h in top_3
                ],
                "bottom_performers": [
                    {
                        "ticker": h.get("ticker"),
                        "weight": h.get("weight"),
                        "composite_z": h.get("composite_z"),
                        "risk_score": h.get("risk_score")
                    }
                    for h in bottom_3
                ]
            },
            recommendations=[
                "Monitor top performers for potential profit-taking",
                "Review underperformers for replacement candidates",
                "Consider rebalancing if performance divergence is significant"
            ]
        ))
        
        return insights
    
    # ========================= Database Persistence =========================
    
    def _save_insight(self, insight: GuardianInsight) -> int:
        """
        Save insight to guardian_insights table
        
        Returns:
            insight_id (primary key)
        """
        with self.postgres.connection.cursor() as cur:
            cur.execute("""
                INSERT INTO guardian_insights (
                    user_id,
                    snapshot_id,
                    insight_type,
                    severity,
                    title,
                    description,
                    metrics,
                    recommendations,
                    vee_explanations,
                    conversational_summary,
                    created_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
                RETURNING insight_id
            """, (
                insight.user_id,
                insight.snapshot_id,
                insight.insight_type,
                insight.severity,
                insight.title,
                insight.description,
                json.dumps(insight.metrics),
                json.dumps(insight.recommendations),
                json.dumps(insight.vee_explanations) if insight.vee_explanations else '{}',
                insight.conversational_summary or None
            ))
            
            insight_id = cur.fetchone()[0]
            self.postgres.connection.commit()
            
            logger.info(f"✅ Insight saved - ID: {insight_id}, Type: {insight.insight_type}")
            if insight.conversational_summary:
                logger.info(f"   Conversational: {insight.conversational_summary[:80]}...")
            return insight_id
    
    def get_user_insights(
        self,
        user_id: str,
        limit: int = 10,
        insight_type: Optional[str] = None
    ) -> List[GuardianInsight]:
        """
        Retrieve insights for user
        
        Args:
            user_id: User identifier
            limit: Maximum number of insights to return
            insight_type: Filter by insight type (optional)
        
        Returns:
            List of GuardianInsight objects
        """
        with self.postgres.connection.cursor() as cur:
            if insight_type:
                cur.execute("""
                    SELECT * FROM guardian_insights
                    WHERE user_id = %s AND insight_type = %s
                    ORDER BY created_at DESC
                    LIMIT %s
                """, (user_id, insight_type, limit))
            else:
                cur.execute("""
                    SELECT * FROM guardian_insights
                    WHERE user_id = %s
                    ORDER BY created_at DESC
                    LIMIT %s
                """, (user_id, limit))
            
            rows = cur.fetchall()
            columns = [desc[0] for desc in cur.description]
            
            insights = []
            for row in rows:
                data = dict(zip(columns, row))
                insights.append(GuardianInsight(
                    insight_id=data["insight_id"],
                    user_id=data["user_id"],
                    snapshot_id=data["snapshot_id"],
                    insight_type=data["insight_type"],
                    severity=data["severity"],
                    title=data["title"],
                    description=data["description"],
                    metrics=data["metrics"],
                    recommendations=data["recommendations"],
                    created_at=data["created_at"]
                ))
            
            return insights


# ========================= Conversational Layer (VEE + ChatGPT) =========================

    def _enhance_with_vee_narratives(self, insight: GuardianInsight) -> GuardianInsight:
        """
        Enhance insight with VEE 3-level narratives + ChatGPT conversational summary.
        
        Golden Rule: ChatGPT fallback ALWAYS available if VEE unavailable.
        MCP Server: Filters/validates via LangGraph (default behavior).
        
        Args:
            insight: Guardian insight to enhance
            
        Returns:
            Enhanced insight with vee_explanations and conversational_summary
        """
        if not self.conversational_mode:
            return insight
        
        # Prepare context for narrative generation
        context = {
            "insight_type": insight.insight_type,
            "severity": insight.severity,
            "title": insight.title,
            "metrics": insight.metrics,
            "recommendations": insight.recommendations
        }
        
        # Strategy 1: VEE Engine (preferred)
        if self.vee_engine:
            try:
                vee_result = self._generate_vee_narratives(insight, context)
                insight.vee_explanations = vee_result
                logger.info(f"✅ VEE narratives generated for {insight.insight_type}")
            except Exception as e:
                logger.warning(f"⚠️ VEE generation failed: {e}, falling back to ChatGPT")
                insight.vee_explanations = self._chatgpt_fallback_vee(context)
        else:
            # Strategy 2: ChatGPT Fallback (Golden Rule)
            insight.vee_explanations = self._chatgpt_fallback_vee(context)
            logger.info(f"✅ ChatGPT VEE fallback for {insight.insight_type}")
        
        # Generate conversational summary (always via ChatGPT for consistency)
        insight.conversational_summary = self._generate_conversational_summary(insight, context)
        
        return insight
    
    def _generate_vee_narratives(self, insight: GuardianInsight, context: Dict) -> Dict[str, str]:
        """
        Generate VEE 3-level narratives (summary, detailed, technical).
        
        Returns:
            Dict with 'summary', 'detailed', 'technical' keys
        """
        # Build pseudo-KPI for VEE (adapt Guardian metrics to VEE format)
        pseudo_kpi = {
            "ticker": context.get("ticker", "PORTFOLIO"),
            "composite_score": context["metrics"].get("average_risk_score", 0.5),
            "momentum_z": 0.0,  # Not applicable for portfolio insights
            "trend_z": 0.0,
            "volatility_z": context["metrics"].get("volatility_score", 0.0),
            "sentiment_z": 0.0,
            "fundamental_z": context["metrics"].get("diversification_score", 0.5),
            "percentile": 50.0,
            "verdict": self._severity_to_verdict(insight.severity),
            "factors": {}  # Portfolio-level factors
        }
        
        # Call VEE engine
        vee_result = self.vee_engine.explain_ticker(
            ticker="PORTFOLIO",  # Guardian insights are portfolio-level, not ticker-specific
            kpi=pseudo_kpi,
            profile=None,
            semantic_context=None
        )
        
        return {
            "summary": vee_result.get("summary", ""),
            "detailed": vee_result.get("detailed", ""),
            "technical": vee_result.get("technical", "")
        }
    
    def _chatgpt_fallback_vee(self, context: Dict) -> Dict[str, str]:
        """
        ChatGPT fallback for VEE narratives (Golden Rule).
        
        Returns:
            Dict with 'summary', 'detailed', 'technical' keys
        """
        if not OPENAI_AVAILABLE:
            logger.warning("⚠️ OpenAI not available, using template fallback")
            return {
                "summary": context.get("title", "Portfolio insight"),
                "detailed": context.get("description", ""),
                "technical": json.dumps(context.get("metrics", {}), indent=2)
            }
        
        # Generate 3-level narratives via ChatGPT
        prompt = f"""
You are Vitruvyan Portfolio Guardian, a conversational AI advisor.

Generate 3-level narratives for this portfolio insight:

Insight Type: {context['insight_type']}
Severity: {context['severity']}
Title: {context['title']}
Metrics: {json.dumps(context['metrics'], indent=2)}
Recommendations: {json.dumps(context['recommendations'])}

Generate:
1. SUMMARY (120-180 words): Conversational, empathetic, zero jargon. Explain what's happening and why it matters.
2. DETAILED (150-200 words): Operational analysis with strategy implications. Use technical concepts but keep accessible.
3. TECHNICAL (200-250 words): Explicit metrics, thresholds, risk scores. Use percentages, z-scores, precise numbers.

Response format (JSON):
{{
  "summary": "...",
  "detailed": "...",
  "technical": "..."
}}
"""
        
        try:
            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                max_tokens=800
            )
            
            content = response.choices[0].message.content
            # Parse JSON response
            narratives = json.loads(content)
            return narratives
        except Exception as e:
            logger.error(f"❌ ChatGPT VEE fallback failed: {e}")
            return {
                "summary": context.get("title", ""),
                "detailed": context.get("description", ""),
                "technical": json.dumps(context.get("metrics", {}), indent=2)
            }
    
    def _generate_conversational_summary(self, insight: GuardianInsight, context: Dict) -> str:
        """
        Generate human-friendly conversational summary (always ChatGPT).
        
        Returns:
            Single-paragraph natural summary (50-80 words)
        """
        if not OPENAI_AVAILABLE:
            return f"{insight.title}: {insight.description}"
        
        prompt = f"""
You are Vitruvyan, a friendly AI portfolio advisor.

Summarize this portfolio insight in 50-80 words, conversational tone:

Type: {insight.insight_type}
Severity: {insight.severity}
Title: {insight.title}
Description: {insight.description}

Write as if explaining to a friend. No bullet points, just natural flow.
"""
        
        try:
            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.8,
                max_tokens=150
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            logger.error(f"❌ ChatGPT summary failed: {e}")
            return f"{insight.title}: {insight.description}"
    
    def _severity_to_verdict(self, severity: str) -> str:
        """Map InsightSeverity to VEE verdict"""
        mapping = {
            "critical": "STRONG_SELL",
            "warning": "MODERATE_HOLD",
            "info": "NEUTRAL"
        }
        return mapping.get(severity, "NEUTRAL")


# ========================= Utility Functions =========================

def analyze_all_portfolios(postgres_agent: PostgresAgent) -> Dict[str, List[GuardianInsight]]:
    """
    Analyze all active portfolios and generate insights
    
    Intended for cron job execution (hourly)
    
    Args:
        postgres_agent: PostgreSQL connection
    
    Returns:
        Dict mapping user_id → List[GuardianInsight]
    """
    logger.info("🛡️ Guardian: Analyzing all portfolios...")
    
    guardian = PortfolioGuardianAgent(postgres_agent=postgres_agent)
    
    # Get all unique users with portfolios
    with postgres_agent.connection.cursor() as cur:
        cur.execute("""
            SELECT DISTINCT user_id
            FROM shadow_portfolio_snapshots
            WHERE created_at > NOW() - INTERVAL '7 days'
        """)
        users = [row[0] for row in cur.fetchall()]
    
    results = {}
    for user_id in users:
        insights = guardian.analyze_portfolio(user_id=user_id)
        results[user_id] = insights
    
    logger.info(f"✅ Guardian analysis complete - {len(users)} users, {sum(len(v) for v in results.values())} total insights")
    return results
