"""Vitruvyan Embedding API — Nomic embedding service — Port 8010."""

import logging
import os
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.responses import Response
from prometheus_client import generate_latest, CONTENT_TYPE_LATEST
from fastapi.middleware.cors import CORSMiddleware
from core.middleware.auth import AuthMiddleware

from .config import get_config
from .api import router
from .services import get_embedding_service

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    config = get_config()
    service = get_embedding_service()
    
    logger.info("=" * 50)
    logger.info("🧮 Vitruvyan Embedding API starting")
    logger.info(f"   Model: {config.model.name}")
    logger.info(f"   Port: {config.service.port}")
    logger.info("=" * 50)
    
    await service.initialize()
    logger.info("🎯 Embedding API ready")
    
    yield
    
    await service.cleanup()
    logger.info("✅ Shutdown complete")


app = FastAPI(
    title="Vitruvyan Embedding API",
    description="MiniLM embedding service for Gemma cooperation",
    version="1.0.0",
    lifespan=lifespan,
)

_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")
app.add_middleware(AuthMiddleware)
app.add_middleware(CORSMiddleware, allow_origins=_ALLOWED_ORIGINS, allow_credentials=True, allow_methods=["*"], allow_headers=["*"])
app.include_router(router)


@app.get("/metrics", tags=["Observability"])
async def metrics():
    """
    Prometheus metrics exposition endpoint for the Embedding API.
    Returns Prometheus plaintext metrics generated by `prometheus_client`.
    """
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


if __name__ == "__main__":
    import uvicorn
    config = get_config()
    uvicorn.run(app, host="0.0.0.0", port=config.service.port, log_level="info")
