"""Memory Orders — Monitoring Package

Metric name constants for dual-memory coherence system.
"""

from .metrics import (
    # Coherence
    COHERENCE_DRIFT_PCT,
    COHERENCE_DRIFT_ABS,
    COHERENCE_STATUS,
    COHERENCE_CHECK_DURATION_S,
    # Health
    HEALTH_STATUS,
    HEALTH_SCORE,
    HEALTH_CHECK_DURATION_S,
    # Component Health
    ARCHIVARIUM_CONNECTED,
    MNEMOSYNE_CONNECTED,
    REDIS_CONNECTED,
    EMBEDDING_API_CONNECTED,
    BABEL_GARDENS_CONNECTED,
    # Sync
    SYNC_OPERATIONS_TOTAL,
    SYNC_DURATION_S,
    SYNC_FAILURES_TOTAL,
    SYNC_LAST_TIMESTAMP,
    # Data
    ARCHIVARIUM_RECORD_COUNT,
    MNEMOSYNE_POINT_COUNT,
    DUAL_MEMORY_QUERIES_TOTAL,
    # Audit
    AUDIT_RECORDS_TOTAL,
    AUDIT_WRITE_DURATION_S,
)

__all__ = [
    # Coherence
    "COHERENCE_DRIFT_PCT",
    "COHERENCE_DRIFT_ABS",
    "COHERENCE_STATUS",
    "COHERENCE_CHECK_DURATION_S",
    # Health
    "HEALTH_STATUS",
    "HEALTH_SCORE",
    "HEALTH_CHECK_DURATION_S",
    # Component Health
    "ARCHIVARIUM_CONNECTED",
    "MNEMOSYNE_CONNECTED",
    "REDIS_CONNECTED",
    "EMBEDDING_API_CONNECTED",
    "BABEL_GARDENS_CONNECTED",
    # Sync
    "SYNC_OPERATIONS_TOTAL",
    "SYNC_DURATION_S",
    "SYNC_FAILURES_TOTAL",
    "SYNC_LAST_TIMESTAMP",
    # Data
    "ARCHIVARIUM_RECORD_COUNT",
    "MNEMOSYNE_POINT_COUNT",
    "DUAL_MEMORY_QUERIES_TOTAL",
    # Audit
    "AUDIT_RECORDS_TOTAL",
    "AUDIT_WRITE_DURATION_S",
]
