services:
  nginx:
    image: nginx:stable
    container_name: core_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - mkdocs_site_public:/var/www/mkdocs/site_public:ro
    networks:
      - monitoring-net
      - core-net

  certbot:
    image: certbot/certbot:latest
    container_name: core_certbot
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do sleep 6h & wait $${!}; done;"]
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
  core-net:
    external: true
    name: vitruvyan_core_net

volumes:
  mkdocs_site_public:
    external: true
    name: vitruvyan-core_mkdocs_site_public
