FROM python:3.12-slim

WORKDIR /app

COPY infrastructure/docker/requirements/requirements.edge_gateway.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY services/api_edge_gateway /app/api_edge_gateway

EXPOSE 9070

CMD ["uvicorn", "api_edge_gateway.main:app", "--host", "0.0.0.0", "--port", "9070"]
