"""
Data Models for Update Manager

Frozen dataclasses (immutable DTOs).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass(frozen=True)
class Release:
    """
    Core release metadata.
    
    Source: GitHub Releases API + release_metadata.json
    """
    version: str
    release_date: datetime
    channel: str  # stable|beta
    contracts_version: str
    changes: dict  # {breaking: [], features: [], fixes: []}
    migration_guide_url: Optional[str] = None
    checksum: Optional[str] = None


@dataclass(frozen=True)
class CompatibilityResult:
    """
    Compatibility check result.
    
    Exit codes:
    - compatible: True → safe to upgrade
    - compatible: False, reason: "..." → blocked
    """
    compatible: bool
    current_version: str
    target_version: str
    reason: Optional[str] = None  # e.g. "contracts_major_mismatch"
    warnings: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class UpgradePlan:
    """
    Upgrade execution plan.
    
    Generated by planner, executed by executor.
    """
    from_version: str
    to_version: str
    changes: dict
    tests_required: List[str]
    estimated_downtime: int  # seconds
    rollback_strategy: str  # e.g. "git_tag_snapshot"
