"""
Data Models for Update Manager

Frozen dataclasses (immutable DTOs).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass(frozen=True)
class Release:
    """
    Core release metadata.
    
    Source: GitHub Releases API + releases.json asset
    """
    version: str
    release_date: str  # ISO 8601 timestamp
    channel: str  # stable|beta
    contracts_version: str
    changes: dict  # {breaking: [], features: [], fixes: []}
    migration_guide_url: Optional[str] = None
    minimum_vertical_version: dict = field(default_factory=dict)  # {vertical_name: min_version}
    checksum: dict = field(default_factory=dict)  # {type: "git_commit_sha", value: "..."}


@dataclass(frozen=True)
class CompatibilityResult:
    """
    Compatibility check result.
    
    Exit codes:
    - compatible: True → safe to upgrade
    - compatible: False, blocking_reason: "..." → blocked
    """
    compatible: bool
    target_version: str
    blocking_reason: Optional[str] = None  # e.g. "contracts_major_mismatch"


@dataclass(frozen=True)
class UpgradePlan:
    """
    Upgrade execution plan.
    
    Generated by planner, executed by executor.
    """
    from_version: str
    to_version: str
    changes: dict
    tests_required: List[str]
    estimated_downtime: int  # seconds
    rollback_strategy: str  # e.g. "git_tag_snapshot"
