"""
Package Manager — Data Models

Frozen dataclasses for package manifests, install plans, and state.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass(frozen=True)
class PackageManifest:
    """
    Parsed .vit manifest file.

    Represents a single installable package with all its metadata.
    """

    package_name: str
    package_version: str
    package_type: str  # service|order|vertical|extension
    status: str  # stable|beta|experimental|deprecated
    tier: str  # core|package
    description: str
    sacred_order: Optional[str] = None  # perception|memory|reason|discourse|truth

    # Compatibility
    min_core_version: str = "1.0.0"
    max_core_version: str = "1.x.x"
    contracts_major: int = 1
    conflicts_with: List[str] = field(default_factory=list)

    # Dependencies
    required_deps: List[str] = field(default_factory=list)
    optional_deps: List[str] = field(default_factory=list)
    system_deps: List[str] = field(default_factory=list)

    # Installation
    install_method: str = "docker_compose"
    compose_service: Optional[str] = None
    compose_file: str = "infrastructure/docker/docker-compose.yml"
    dockerfile: Optional[str] = None
    ports: List[str] = field(default_factory=list)
    env_required: List[str] = field(default_factory=list)
    env_optional: List[str] = field(default_factory=list)
    init_commands: List[str] = field(default_factory=list)

    # Vertical-specific (components list)
    components: List[Dict] = field(default_factory=list)

    # Health
    health_endpoint: Optional[str] = None
    health_interval: int = 30
    health_timeout: int = 10

    # Smoke tests
    smoke_test_path: Optional[str] = None
    smoke_test_timeout: int = 120

    # Uninstallation
    preserve_data: bool = True
    cleanup_streams: bool = False
    cleanup_channels: List[str] = field(default_factory=list)
    cleanup_commands: List[str] = field(default_factory=list)

    # Ownership
    team: str = ""
    contact: str = ""

    # Source file path (set after parsing)
    manifest_path: Optional[str] = None

    @property
    def short_name(self) -> str:
        """Package name without type prefix: 'service-neural-engine' → 'neural-engine'."""
        parts = self.package_name.split("-", 1)
        return parts[1] if len(parts) > 1 else self.package_name

    @property
    def cli_name(self) -> str:
        """CLI-friendly name: 'service-neural-engine' → 'neural_engine'."""
        return self.short_name.replace("-", "_")


@dataclass(frozen=True)
class InstalledPackage:
    """
    Record of an installed package in the local state.

    Stored in .vitruvyan/installed_packages.json.
    """

    name: str
    version: str
    installed_at: str  # ISO 8601
    install_method: str
    status: str = "active"  # active|disabled|error
    ports: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class InstallPlan:
    """
    Computed installation plan for one or more packages.

    Generated by resolver, executed by installer.
    """

    target: str  # Primary package to install
    target_version: str
    install_order: List[str] = field(default_factory=list)  # Topological order
    already_installed: List[str] = field(default_factory=list)
    missing_system_deps: List[str] = field(default_factory=list)
    conflicts: List[str] = field(default_factory=list)
    can_proceed: bool = True
    block_reason: Optional[str] = None
