#!/usr/bin/env python3
"""
RiskGuardian — Continuous Risk Monitoring Consumer (Amygdala)
==============================================================

Epistemic Order: TRUTH (Risk Surveillance)
Sacred Order: Sentinel (#7)
Consumer Type: CRITICAL

Biological Model: Amygdala
- Fast, parallel threat detection
- Can interrupt normal processing flow
- Continuous monitoring of all events
- Risk escalation when thresholds exceeded

Subscriptions:
- * (all events) → Monitor everything for risk signals

Capabilities:
- Portfolio volatility monitoring (VARE integration)
- Concentration risk detection (>40% single position)
- Market anomaly detection (extreme z-scores)
- Correlation risk assessment
- Can emit INTERRUPT events that override normal flow

Risk Levels:
- LOW (0.0-0.3): Normal operations
- MEDIUM (0.3-0.6): Warning issued
- HIGH (0.6-0.8): Alert issued + escalation
- CRITICAL (0.8-1.0): INTERRUPT issued + immediate action

Author: Vitruvyan Cognitive Architecture  
Date: January 20, 2026  
Phase: 5 (Specialized Consumers)
"""

import asyncio
import json
import logging
import time
from typing import Dict, Any, Optional, List, Tuple
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from enum import Enum

from .base_consumer import (
    BaseConsumer,
    ConsumerConfig,
    ConsumerType,
    ProcessResult
)
from ..streams import StreamEvent
from ..event_envelope import CognitiveEvent, TransportEvent, EventAdapter
from .working_memory import WorkingMemory
from vitruvyan_core.core.foundation.persistence.postgres_agent import PostgresAgent

logger = logging.getLogger("RiskGuardian")


class RiskLevel(Enum):
    """Risk severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class RiskAlert:
    """
    Risk alert generated by Sentinel.
    
    Attributes:
        risk_type: Type of risk detected
        risk_level: Severity (LOW/MEDIUM/HIGH/CRITICAL)
        risk_score: Numeric risk score (0-1)
        description: Human-readable description
        affected_entities: Tickers/portfolios affected
        recommended_action: What to do about it
        can_interrupt: Whether this triggers INTERRUPT event
        metadata: Additional context
    """
    risk_type: str
    risk_level: RiskLevel
    risk_score: float
    description: str
    affected_entities: List[str]
    recommended_action: str
    can_interrupt: bool = False
    metadata: Dict[str, Any] = None
    timestamp: str = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow().isoformat()
    
    def to_dict(self) -> Dict[str, Any]:
        result = asdict(self)
        result["risk_level"] = self.risk_level.value
        return result


class RiskGuardian(BaseConsumer):
    """
    Critical consumer for continuous risk monitoring.
    
    Like amygdala: fast, parallel, can interrupt.
    Always responds (even if just "no risk detected").
    
    Monitors:
    - Portfolio volatility (VARE integration)
    - Concentration risk (holdings > 40% single ticker)
    - Extreme z-scores (composite > 2.5 or < -2.5)
    - Correlation risk (high correlation across portfolio)
    - Market anomalies (volume spikes, price crashes)
    
    Can emit:
    - risk.alert.* → Warning/alert events
    - risk.interrupt → INTERRUPT event that overrides normal flow
    """
    
    # Risk thresholds (configurable)
    VOLATILITY_WARNING_THRESHOLD = 0.25  # 25% annualized vol
    VOLATILITY_CRITICAL_THRESHOLD = 0.50  # 50% annualized vol
    CONCENTRATION_WARNING_THRESHOLD = 0.40  # 40% single position
    CONCENTRATION_CRITICAL_THRESHOLD = 0.60  # 60% single position
    ZSCORE_WARNING_THRESHOLD = 2.0  # Z-score magnitude
    ZSCORE_CRITICAL_THRESHOLD = 3.0  # Extreme z-score
    
    def __init__(
        self,
        redis_url: str = "redis://vitruvyan_redis:6379",
        postgres_agent: Optional[PostgresAgent] = None
    ):
        """
        Initialize RiskGuardian consumer.
        
        Args:
            redis_url: Redis connection URL
            postgres_agent: Optional PostgresAgent (creates new if None)
        """
        # Configure consumer as CRITICAL (must always respond)
        config = ConsumerConfig(
            name="risk_guardian",
            consumer_type=ConsumerType.CRITICAL,
            subscriptions=["*"],  # Monitor ALL events
            confidence_threshold=0.9,  # High confidence required
            timeout_ms=2000  # Fast response (2s max)
        )
        
        super().__init__(config)
        
        # Initialize PostgreSQL agent for risk logging
        self.postgres = postgres_agent or PostgresAgent()
        
        # Initialize working memory (Redis-backed)
        self.memory = WorkingMemory(
            consumer_name="risk_guardian",
            ttl_seconds=86400  # Remember risk state for 24h
        )
        
        # Connect to Redis
        asyncio.create_task(self.memory.connect(redis_url))
        
        # Risk state tracking
        self.active_alerts: List[RiskAlert] = []
        self.alert_history: List[RiskAlert] = []
        
        logger.info(f"🛡️ RiskGuardian initialized (CRITICAL consumer)")
        logger.info(f"   Subscriptions: ALL EVENTS (*)")
        logger.info(f"   Volatility thresholds: {self.VOLATILITY_WARNING_THRESHOLD}/{self.VOLATILITY_CRITICAL_THRESHOLD}")
        logger.info(f"   Concentration thresholds: {self.CONCENTRATION_WARNING_THRESHOLD}/{self.CONCENTRATION_CRITICAL_THRESHOLD}")
        logger.info(f"   Timeout: {config.timeout_ms}ms")
    
    async def process(self, event: CognitiveEvent) -> ProcessResult:
        """
        Process incoming events for risk detection.
        
        CRITICAL consumer: MUST always respond, even if "no risk".
        
        Risk checks:
        1. Portfolio volatility (from VARE data)
        2. Concentration risk (single position > threshold)
        3. Extreme z-scores (outlier detection)
        4. Correlation risk (portfolio over-correlated)
        
        Args:
            event: Incoming stream event
            
        Returns:
            StreamEvent with risk assessment (or INTERRUPT if critical)
        """
        # Convert TransportEvent to CognitiveEvent if needed
        if isinstance(event, TransportEvent):
            event = EventAdapter.transport_to_cognitive(event)
        
        event_type = event.type if hasattr(event, 'type') else event.stream
        
        try:
            # Risk detection routing
            risks: List[RiskAlert] = []
            
            # Check for portfolio-related events
            if "portfolio" in event_type:
                risks.extend(await self._check_portfolio_risks(event))
            
            # Check for analysis events (z-scores)
            if "analysis" in event_type and "complete" in event_type:
                risks.extend(await self._check_zscore_risks(event))
            
            # Check for screening events (multiple tickers)
            if "screening" in event_type and "complete" in event_type:
                risks.extend(await self._check_concentration_risks(event))
            
            # Check for market anomalies
            if "market" in event_type and "update" in event_type:
                risks.extend(await self._check_market_anomalies(event))
            
            # Determine highest risk level
            risk_level = self._get_max_risk_level(risks)
            
            # Log to PostgreSQL
            await self._log_risk_assessment(event, risks, risk_level)
            
            # Store in memory for trend analysis
            await self._remember_risk_state(event, risks)
            
            # Emit INTERRUPT if critical risk
            if risk_level == RiskLevel.CRITICAL:
                return await self._emit_interrupt(event, risks)
            
            # Emit regular alert if HIGH risk
            if risk_level == RiskLevel.HIGH:
                return await self._emit_alert(event, risks, "high")
            
            # Emit warning if MEDIUM risk
            if risk_level == RiskLevel.MEDIUM:
                return await self._emit_alert(event, risks, "medium")
            
            # No significant risk - emit confirmation (CRITICAL must respond)
            return ProcessResult.emit(event.child(
                event_type="risk.assessment_complete",
                payload={
                    "risk_level": "low",
                    "risk_score": 0.0,
                    "risks_detected": [],
                    "message": "No significant risks detected."
                },
                source=self.config.name
            ))
            
        except Exception as e:
            logger.error(f"❌ Sentinel processing failed: {e}")
            # CRITICAL consumer - must respond even on error
            return ProcessResult.emit(event.child(
                event_type="risk.assessment_error",
                payload={
                    "error": str(e),
                    "message": "Risk assessment failed, defaulting to CAUTION."
                },
                source=self.config.name
            ))
    
    async def _check_portfolio_risks(self, event: CognitiveEvent) -> List[RiskAlert]:
        """
        Check portfolio-specific risks.
        
        Checks:
        - Volatility (VARE integration)
        - Concentration (single position > threshold)
        - Diversification (too few holdings)
        
        Args:
            event: Event with portfolio data
            
        Returns:
            List of risk alerts
        """
        risks = []
        payload = event.payload
        portfolio_data = payload.get("portfolio_data", {})
        
        if not portfolio_data:
            return risks
        
        holdings = portfolio_data.get("holdings", [])
        total_value = portfolio_data.get("total_value", 0)
        
        # Check concentration risk
        for holding in holdings:
            ticker = holding.get("ticker")
            value = holding.get("value", 0)
            weight = value / total_value if total_value > 0 else 0
            
            if weight > self.CONCENTRATION_CRITICAL_THRESHOLD:
                risks.append(RiskAlert(
                    risk_type="concentration_critical",
                    risk_level=RiskLevel.CRITICAL,
                    risk_score=weight,
                    description=f"{ticker} represents {weight*100:.1f}% of portfolio (critical threshold: {self.CONCENTRATION_CRITICAL_THRESHOLD*100:.0f}%)",
                    affected_entities=[ticker],
                    recommended_action=f"REDUCE {ticker} position immediately to <50%",
                    can_interrupt=True
                ))
            elif weight > self.CONCENTRATION_WARNING_THRESHOLD:
                risks.append(RiskAlert(
                    risk_type="concentration_warning",
                    risk_level=RiskLevel.HIGH,
                    risk_score=weight,
                    description=f"{ticker} represents {weight*100:.1f}% of portfolio (warning threshold: {self.CONCENTRATION_WARNING_THRESHOLD*100:.0f}%)",
                    affected_entities=[ticker],
                    recommended_action=f"Consider diversifying away from {ticker}"
                ))
        
        # Check diversification (too few holdings)
        if len(holdings) < 3:
            risks.append(RiskAlert(
                risk_type="under_diversified",
                risk_level=RiskLevel.MEDIUM,
                risk_score=0.6,
                description=f"Portfolio has only {len(holdings)} holdings (recommended: 5+)",
                affected_entities=[h.get("ticker") for h in holdings],
                recommended_action="Increase diversification with additional positions"
            ))
        
        return risks
    
    async def _check_zscore_risks(self, event: CognitiveEvent) -> List[RiskAlert]:
        """
        Check for extreme z-scores (outlier detection).
        
        Z-score magnitude > 2.5 indicates unusual behavior.
        
        Args:
            event: Event with analysis data
            
        Returns:
            List of risk alerts
        """
        risks = []
        payload = event.payload
        kpi = payload.get("kpi", {})
        ticker = payload.get("ticker", "UNKNOWN")
        
        # Check composite z-score
        composite_z = kpi.get("composite_z", 0)
        
        if abs(composite_z) > self.ZSCORE_CRITICAL_THRESHOLD:
            risks.append(RiskAlert(
                risk_type="extreme_zscore",
                risk_level=RiskLevel.HIGH,
                risk_score=min(abs(composite_z) / 4.0, 1.0),  # Normalize to 0-1
                description=f"{ticker} composite z-score {composite_z:.2f} is extreme (threshold: ±{self.ZSCORE_CRITICAL_THRESHOLD})",
                affected_entities=[ticker],
                recommended_action=f"Investigate {ticker} for anomalies or data issues"
            ))
        elif abs(composite_z) > self.ZSCORE_WARNING_THRESHOLD:
            risks.append(RiskAlert(
                risk_type="high_zscore",
                risk_level=RiskLevel.MEDIUM,
                risk_score=min(abs(composite_z) / 3.0, 1.0),
                description=f"{ticker} composite z-score {composite_z:.2f} is elevated (threshold: ±{self.ZSCORE_WARNING_THRESHOLD})",
                affected_entities=[ticker],
                recommended_action=f"Monitor {ticker} for continued unusual behavior"
            ))
        
        return risks
    
    async def _check_concentration_risks(self, event: CognitiveEvent) -> List[RiskAlert]:
        """
        Check concentration risks in screening results.
        
        If top-ranked ticker dominates, may indicate over-concentration.
        
        Args:
            event: Event with screening data
            
        Returns:
            List of risk alerts
        """
        risks = []
        payload = event.payload
        screening_data = payload.get("screening_data", [])
        
        if len(screening_data) < 2:
            return risks
        
        # Check if rank 1 significantly dominates rank 2
        rank1 = screening_data[0]
        rank2 = screening_data[1]
        
        rank1_composite = rank1.get("composite_z", 0)
        rank2_composite = rank2.get("composite_z", 0)
        
        # If rank 1 is >2 standard deviations above rank 2, flag
        if rank1_composite - rank2_composite > 2.0:
            risks.append(RiskAlert(
                risk_type="dominant_single_ticker",
                risk_level=RiskLevel.MEDIUM,
                risk_score=0.5,
                description=f"{rank1.get('ticker')} dominates screening (composite {rank1_composite:.2f} vs {rank2.get('ticker')} {rank2_composite:.2f})",
                affected_entities=[rank1.get("ticker")],
                recommended_action="Consider diversification beyond single dominant ticker"
            ))
        
        return risks
    
    async def _check_market_anomalies(self, event: CognitiveEvent) -> List[RiskAlert]:
        """
        Check for market-wide anomalies.
        
        Placeholder for future implementation:
        - Volume spikes
        - Price crashes
        - Correlation breakdowns
        
        Args:
            event: Event with market data
            
        Returns:
            List of risk alerts
        """
        # TODO: Implement market anomaly detection
        return []
    
    def _get_max_risk_level(self, risks: List[RiskAlert]) -> RiskLevel:
        """Get highest risk level from list of risks."""
        if not risks:
            return RiskLevel.LOW
        
        priority = {
            RiskLevel.CRITICAL: 4,
            RiskLevel.HIGH: 3,
            RiskLevel.MEDIUM: 2,
            RiskLevel.LOW: 1
        }
        
        max_risk = max(risks, key=lambda r: priority[r.risk_level])
        return max_risk.risk_level
    
    async def _emit_interrupt(
        self,
        event: CognitiveEvent,
        risks: List[RiskAlert]
    ) -> StreamEvent:
        """
        Emit INTERRUPT event for critical risk.
        
        INTERRUPT events override normal flow and require immediate action.
        
        Args:
            event: Original event
            risks: Critical risks detected
            
        Returns:
            INTERRUPT StreamEvent
        """
        logger.critical(f"🚨 CRITICAL RISK DETECTED - INTERRUPTING")
        for risk in risks:
            if risk.risk_level == RiskLevel.CRITICAL:
                logger.critical(f"   {risk.description}")
        
        return ProcessResult.emit(event.child(
            event_type="risk.interrupt",  # Special stream that overrides normal flow
            payload={
                "risk_level": "critical",
                "risks": [r.to_dict() for r in risks],
                "interrupt_reason": "Critical risk threshold exceeded",
                "immediate_action_required": True
            },
            source=self.config.name
        ))
    
    async def _emit_alert(
        self,
        event: CognitiveEvent,
        risks: List[RiskAlert],
        severity: str
    ) -> StreamEvent:
        """
        Emit risk alert event.
        
        Args:
            event: Original event
            risks: Risks detected
            severity: "high" or "medium"
            
        Returns:
            Alert StreamEvent
        """
        logger.warning(f"⚠️ RISK ALERT ({severity.upper()})")
        for risk in risks:
            logger.warning(f"   {risk.description}")
        
        return ProcessResult.emit(event.child(
            event_type=f"risk.alert_{severity}",
            payload={
                "risk_level": severity,
                "risks": [r.to_dict() for r in risks]
            },
            source=self.config.name
        ))
    
    async def _log_risk_assessment(
        self,
        event: CognitiveEvent,
        risks: List[RiskAlert],
        risk_level: RiskLevel
    ) -> None:
        """
        Log risk assessment to PostgreSQL.
        
        Table: sentinel_risk_assessments
        
        Args:
            event: Original event
            risks: Risks detected
            risk_level: Maximum risk level
        """
        try:
            # TODO: Implement PostgreSQL logging
            # self.postgres.insert_risk_assessment(...)
            pass
        except Exception as e:
            logger.warning(f"⚠️ Failed to log risk assessment: {e}")
    
    async def _remember_risk_state(
        self,
        event: CognitiveEvent,
        risks: List[RiskAlert]
    ) -> None:
        """
        Store risk state in working memory for trend analysis.
        
        Args:
            event: Original event
            risks: Risks detected
        """
        try:
            # Store last assessment
            await self.memory.remember(
                key="risk:last_assessment",
                value={
                    "event_id": event.id,
                    "event_type": event.type,
                    "num_risks": len(risks),
                    "max_risk_level": self._get_max_risk_level(risks).value,
                    "timestamp": datetime.utcnow().isoformat()
                }
            )
            
            # Store per-ticker risk (for portfolio tracking)
            for risk in risks:
                for entity in risk.affected_entities:
                    await self.memory.remember(
                        key=f"risk:ticker:{entity}",
                        value={
                            "risk_type": risk.risk_type,
                            "risk_level": risk.risk_level.value,
                            "risk_score": risk.risk_score,
                            "timestamp": risk.timestamp
                        }
                    )
                    
        except Exception as e:
            logger.warning(f"⚠️ Failed to store risk state: {e}")


# Example standalone usage
if __name__ == "__main__":
    async def main():
        # Initialize consumer
        sentinel = RiskGuardian()
        
        # Test portfolio concentration risk
        test_event = CognitiveEvent(
            type="portfolio.analysis.complete",
            correlation_id="test-123",
            causation_id=None,
            trace_id="trace-123",
            source="portfolio_analysis",
            payload={
                "portfolio_data": {
                    "holdings": [
                        {"ticker": "AAPL", "value": 70000, "shares": 500},
                        {"ticker": "NVDA", "value": 20000, "shares": 100},
                        {"ticker": "MSFT", "value": 10000, "shares": 50}
                    ],
                    "total_value": 100000
                }
            },
            metadata={}
        )
        
        result = await sentinel.process(test_event)
        
        if result:
            print(f"✅ Risk assessment: {result.type}")
            print(json.dumps(result.payload, indent=2))
        else:
            print("❌ No risk assessment generated")
    
    asyncio.run(main())
