/**
 * MODE SELECTION UI - Multi-Ticker Analysis Mode Clarification
 * 
 * Purpose: When user enters 2+ tickers without explicit keywords (confronta/alloca),
 * Vitruvyan asks which analysis mode they prefer via conversational narrative + 3 buttons.
 * 
 * Flow:
 * 1. Show Vitruvyan's conversational narrative (with typewriter effect)
 * 2. Display 3 mode buttons: Comparison / Allocation / Screening
 * 3. On click → call onModeSelect(mode) → backend re-runs with mode_choice parameter
 * 
 * Props:
 * - narrative: string - Vitruvyan's conversational explanation (generated by ConversationalLLM)
 * - modeOptions: array - [{mode, label, description}]
 * - tickers: array - List of detected ticker symbols
 * - tickerDetails: array - [{ticker, name, sector}]
 * - onModeSelect: function(mode) - Callback when user clicks mode button
 * - className: string
 * 
 * Backend Node: compose_node.py (action='clarify_mode')
 * State Keys: state.response.mode_options, state.response.narrative
 * 
 * Created: Dec 10, 2025
 */

'use client'

import { useState, useEffect } from 'react'
import { BarChart3, PieChart, TrendingUp, Sparkles } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'

// Typewriter effect component
function Typewriter({ text, onComplete }) {
  const [displayed, setDisplayed] = useState('')
  
  useEffect(() => {
    if (!text) return
    
    let index = 0
    let cancelled = false
    
    const timer = setInterval(() => {
      if (cancelled) return
      
      if (index < text.length) {
        setDisplayed(text.slice(0, index + 1))
        index++
      } else {
        clearInterval(timer)
        if (onComplete) onComplete()
      }
    }, 15) // 15ms per character = natural typing speed
    
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [text, onComplete])
  
  return (
    <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
      {displayed}
    </div>
  )
}

export default function ModeSelectionUI({
  narrative,
  modeOptions = [],
  tickers = [],
  tickerDetails = [],
  onModeSelect,
  className = ''
}) {
  const [typingComplete, setTypingComplete] = useState(false)
  const [selectedMode, setSelectedMode] = useState(null)
  
  // Icon mapping for mode buttons
  const modeIcons = {
    comparison: BarChart3,
    allocation: PieChart,
    screening: TrendingUp
  }
  
  // Color mapping for mode buttons
  const modeColors = {
    comparison: 'from-purple-500 to-indigo-600',
    allocation: 'from-green-500 to-emerald-600',
    screening: 'from-blue-500 to-cyan-600'
  }
  
  const handleModeClick = (mode) => {
    setSelectedMode(mode)
    
    // Slight delay for visual feedback before callback
    setTimeout(() => {
      if (onModeSelect) {
        onModeSelect(mode)
      }
    }, 300)
  }
  
  return (
    <div className={`space-y-6 ${className}`}>
      
      {/* Vitruvyan Avatar + Narrative (Conversational) */}
      <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6">
        <div className="flex items-start gap-4">
          {/* Vitruvyan Avatar */}
          <div className="flex-shrink-0">
            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-vitruvyan-accent to-purple-600 flex items-center justify-center shadow-lg">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
          </div>
          
          {/* Narrative with Typewriter */}
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-3">
              <span className="font-semibold text-gray-900">Vitruvyan</span>
              <Badge variant="outline" className="text-xs">AI Advisor</Badge>
            </div>
            
            {narrative && (
              <Typewriter 
                text={narrative} 
                onComplete={() => setTypingComplete(true)}
              />
            )}
          </div>
        </div>
      </div>
      
      {/* Ticker Badges */}
      {tickerDetails && tickerDetails.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {tickerDetails.map((detail) => (
            <Badge 
              key={detail.ticker} 
              variant="secondary" 
              className="text-xs px-3 py-1"
            >
              <span className="font-bold">{detail.ticker}</span>
              {detail.name && detail.name !== detail.ticker && (
                <span className="ml-1 text-gray-500">({detail.name})</span>
              )}
            </Badge>
          ))}
        </div>
      )}
      
      {/* Mode Selection Buttons (Show after typing complete or immediately if no narrative) */}
      {(typingComplete || !narrative) && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {modeOptions.map((option) => {
            const Icon = modeIcons[option.mode] || BarChart3
            const isSelected = selectedMode === option.mode
            
            return (
              <button
                key={option.mode}
                onClick={() => handleModeClick(option.mode)}
                disabled={!!selectedMode}
                className={`
                  group relative overflow-hidden rounded-xl border-2 p-6 text-left
                  transition-all duration-300 transform
                  ${isSelected 
                    ? 'border-purple-500 scale-105 shadow-xl' 
                    : 'border-gray-200 hover:border-gray-300 hover:scale-105 hover:shadow-lg'
                  }
                  ${selectedMode && !isSelected ? 'opacity-50' : ''}
                  disabled:cursor-not-allowed
                `}
              >
                {/* Gradient Background (on hover/select) */}
                <div 
                  className={`
                    absolute inset-0 bg-gradient-to-br opacity-0 
                    transition-opacity duration-300
                    ${isSelected ? 'opacity-10' : 'group-hover:opacity-5'}
                    ${modeColors[option.mode]}
                  `}
                />
                
                {/* Content */}
                <div className="relative z-10">
                  {/* Icon + Label */}
                  <div className="flex items-center gap-3 mb-3">
                    <div className={`
                      w-10 h-10 rounded-lg flex items-center justify-center
                      bg-gradient-to-br ${modeColors[option.mode]}
                      transition-transform duration-300
                      ${isSelected ? 'scale-110' : 'group-hover:scale-110'}
                    `}>
                      <Icon className="w-5 h-5 text-white" />
                    </div>
                    <span className="font-semibold text-gray-900 text-sm">
                      {option.label}
                    </span>
                  </div>
                  
                  {/* Description */}
                  <p className="text-xs text-gray-600 leading-relaxed">
                    {option.description}
                  </p>
                  
                  {/* Selected Indicator */}
                  {isSelected && (
                    <div className="mt-3 flex items-center gap-2 text-xs text-purple-600 font-medium">
                      <div className="w-2 h-2 rounded-full bg-purple-600 animate-pulse" />
                      Processing...
                    </div>
                  )}
                </div>
              </button>
            )
          })}
        </div>
      )}
      
      {/* Helper Text (shown before typing complete) */}
      {!typingComplete && narrative && (
        <div className="text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gray-100 text-xs text-gray-500">
            <div className="flex gap-1">
              <div className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-pulse" />
              <div className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-pulse delay-75" />
              <div className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-pulse delay-150" />
            </div>
            <span>Vitruvyan is thinking...</span>
          </div>
        </div>
      )}
      
    </div>
  )
}
